name: Build and Deploy Full Stack App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install Node.js for React build
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Build React frontend
      - name: Install frontend dependencies
        working-directory: BodybuilderRPG/bodybuilderrpg.client
        run: npm install

      - name: Build frontend
        working-directory: BodybuilderRPG/bodybuilderrpg.client
        run: npm run build

      # Copy React build output into ASP.NET wwwroot
      - name: Copy frontend to backend
        run: |
          rm -rf BodybuilderRPG/BodybuilderRPG.Server/wwwroot/*
          cp -r BodybuilderRPG/bodybuilderrpg.client/dist/* BodybuilderRPG/BodybuilderRPG.Server/wwwroot/

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Restore, build, publish backend
      - name: Restore dependencies
        run: dotnet restore BodybuilderRPG/BodybuilderRPG.Server/BodybuilderRPG.Server.csproj

      - name: Build backend
        run: dotnet build BodybuilderRPG/BodybuilderRPG.Server/BodybuilderRPG.Server.csproj --configuration Release --no-restore

      - name: Publish backend
        run: dotnet publish BodybuilderRPG/BodybuilderRPG.Server/BodybuilderRPG.Server.csproj -c Release -o ./publish --no-build

      # Deploy to Azure (with OIDC)
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: BodybuilderRPG
          package: ./publish




